version: 2
jobs:
  build:
    working_directory: /go/src/github.com/31z4/surge
    docker:
      - image: golang:1.13
    steps:
      - checkout

      - run: out=`gofmt -l .`; if [ ! -z "$out" ]; then echo -e $out; false; fi
      - run: go vet ./...

      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
